namespace: base-chart
replicaCount: 1

image:
  repository: redis
  tag: "7.2.4-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
