apiVersion: v1
kind: Service
metadata:
  name: oai-amf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "amf") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: oai-amf
  ports:
  - name: sbi
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: ngap
    port: 38412
    targetPort: 38412
    protocol: SCTP
