apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-amf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "amf") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oai-amf
  template:
    metadata:
      labels:
        app: oai-amf
        app.kubernetes.io/name: oai-core-cn5g
        app.kubernetes.io/component: amf
    spec:
      containers:
      - name: amf
        image: {{ index .Values.images "amf" }}
        ports:
        - name: sbi
          containerPort: 8080
          protocol: TCP
        - name: ngap
          containerPort: 38412
          protocol: SCTP
        env:
        - name: INT_ALGO_LIST
          value: "NIA2 NIA1 NIA3"
        - name: CIPH_ALGO_LIST
          value: "NEA2 NEA1 NEA3"
        volumeMounts:
        - name: amf-config
          mountPath: /openair-amf/etc/config.yaml
          subPath: config.yaml
      volumes:
      - name: amf-config
        configMap:
          name: oai-amf-config
