apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oai-mysql-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: oai-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
