apiVersion: v1
kind: Service
metadata:
  name: oai-nrf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "nrf") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: oai-nrf
  ports:
  - name: sbi
    port: 80
    targetPort: 8080
    protocol: TCP
