apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nrf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "nrf") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oai-nrf
  template:
    metadata:
      labels:
        app: oai-nrf
        app.kubernetes.io/name: oai-core-cn5g
        app.kubernetes.io/component: nrf
    spec:
      containers:
      - name: nrf
        image: {{ index .Values.images "nrf" }}
        ports:
        - name: sbi
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: nrf-config
          mountPath: /openair-nrf/etc/config.yaml
          subPath: config.yaml
      volumes:
      - name: nrf-config
        configMap:
          name: oai-nrf-config
