apiVersion: v1
kind: Service
metadata:
  name: oai-smf
  namespace: {{ .Values.namespace }}
  labels:
    app: oai-smf
spec:
  type: {{ .Values.smf.service.type | default "ClusterIP" }}
  selector:
    app: oai-smf
  ports:
  - name: sbi
    port: {{ .Values.smf.sbiPort | default 443 }}
    targetPort: {{ .Values.smf.sbiPort | default 443 }}
    protocol: TCP
  {{- if .Values.smf.metricsPort }}
  - name: metrics
    port: {{ .Values.smf.metricsPort }}
    targetPort: {{ .Values.smf.metricsPort }}
    protocol: TCP
  {{- end }}
