apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-smf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "smf") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oai-smf
  template:
    metadata:
      labels:
        app: oai-smf
        app.kubernetes.io/name: oai-core-cn5g
        app.kubernetes.io/component: smf
    spec:
      containers:
      - name: smf
        image: {{ index .Values.images "smf" }}
        ports:
        - name: sbi
          containerPort: 8080
          protocol: TCP
        - name: n4
          containerPort: 8805
          protocol: UDP
        - name: http
          containerPort: 8080
          protocol: TCP

        volumeMounts:
        - name: smf-config
          mountPath: /openair-smf/etc/config.yaml
          subPath: config.yaml
      volumes:
      - name: smf-config
        configMap:
          name: oai-smf-config
