apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-udm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "udm") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oai-udm
  template:
    metadata:
      labels:
        app: oai-udm
        app.kubernetes.io/name: oai-core-cn5g
        app.kubernetes.io/component: udm
    spec:
      containers:
      - name: udm
        image: {{ index .Values.images "udm" }}
        ports:
        - name: sbi
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: udm-config
          mountPath: /openair-udm/etc/config.yaml
          subPath: config.yaml
      volumes:
      - name: udm-config
        configMap:
          name: oai-udm-config
