apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-udr-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oai-core-cn5g.componentLabels" (dict "Values" .Values "Chart" .Chart "Release" .Release "component" "udr") | nindent 4 }}
data:
  config.yaml: |-
    log_level:
      general: debug
    register_nf:
      general: yes
    http_version: 1 #2
    udr:
      host: oai-udr
      sbi:
        addr4: "0.0.0.0"
        port: 8080
        api_version: v1
    nrf:
      host: oai-nrf
      sbi:
        port: 8080
        api_version: v1
    database:
      host: oai-mysql
      user: test
      type: mysql
      password: test
      database_name: oai_db
      connection_timeout: 300
