repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  timeout: 900
  atomic: true
  cleanupOnFail: true
  createNamespace: true

releases:
  # Deploy Redis first
  - name: redis
    namespace: base-chart
    chart: ./charts/redis #bitnami/redis
    values:
      - ../charts/redis/values.yaml        
      - replicaCount: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - name: oai-core
    namespace: base-chart
    chart: ./charts/oai-core
    values:
      - ./charts/oai-core/values.yaml

  - name: ueransim-gnb
    namespace: base-chart
    chart: ./charts/ueransim-gnb
    needs:
      - base-chart/oai-core
    values:
      - ./charts/ueransim-gnb/values.yaml

  - name: ueransim-ue
    namespace: base-chart
    chart: ./charts/ueransim-ue
    needs:
      - base-chart/ueransim-gnb
    values:
      - ./charts/ueransim-ue/values.yaml

  # 5. Mosaic-5G Control Layer
  - name: mosaic5g-controller
    namespace: base-chart
    chart: ./charts/mosaic
    values:
      - ../charts/mosaic/mosaic_values.yaml        
        
  - name: orchestrator
    namespace: base-chart
    chart: ./charts/orchestrator
    values:
      - ../charts/orchestrator/values.yaml

  # 3. FlexRIC (The RIC Platform)
  - name: flexric
    namespace: base-chart
    chart: ./charts/flexric
    values:
      - ../charts/flexric/values.yaml

