/**
* SMF Internal Context Transfer API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ContextTransferApi.h
 *
 * 
 */

#ifndef ContextTransferApi_H_
#define ContextTransferApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "model/PduSessionContextTransfer.h"
#include <string>

#include "../../oai-cn5g-common-src/model/common_model/Snssai.h"
#include "model/Helpers.h"
#include "model/UpfResumeRequest.h"
#include "nlohmann/json.hpp"

namespace oai {
  namespace app {
    namespace smf {
      struct imported_pdu_context;
    }  // namespace smf
  }  // namespace app
}  // namespace oai

namespace oai::smf_server::api
{

class  ContextTransferApi : public ApiBase {
public:
    explicit ContextTransferApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~ContextTransferApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void bind_sm_context_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void export_sm_context_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void import_sm_context_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void pause_sm_context_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void context_transfer_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    // void get_sm_context(const std::string &supi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Bind imported context (activate)
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi"></param>
    /// <param name="pduSessionId"></param>
    virtual void bind_sm_context(const std::string &supi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Export transferable context
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi"></param>
    /// <param name="pduSessionId"></param>
    virtual void export_sm_context(const std::string &supi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Import transferable context (stage)
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi"></param>
    /// <param name="pduSessionId"></param>
    /// <param name="pduSessionContextTransfer"></param>
    virtual void import_sm_context(const std::string &supi, const int32_t &pduSessionId, const oai::model::smf::PduSessionContextTransfer &pduSessionContextTransfer, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Pause PDU session and export transferable context
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supi"></param>
    /// <param name="pduSessionId"></param>
    virtual void pause_sm_context(const std::string &supi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;

    virtual void get_sm_context(const std::string &supi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;

    // Orchra - consider using supi
    virtual void create_pdu_session_context(const std::string &imsi, const int32_t &pduSessionId, const nlohmann::json &body, Pistache::Http::ResponseWriter &response) = 0;
    virtual void pause_pdu_session(const std::string &imsi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
    virtual void get_pdu_session_context(const std::string &imsi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
    // virtual void import_pdu_session_context(const std::string &imsi, const int32_t &pduSessionId, const std::string &body, Pistache::Http::ResponseWriter &response) = 0;
    virtual bool import_pdu_session_context(const oai::app::smf::imported_pdu_context& data, Pistache::Http::ResponseWriter& response) = 0;
    virtual void bind_pdu_session_context(const std::string &imsi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
    virtual void resume_pdu_session(const std::string &imsi, const int32_t &pduSessionId, const oai::model::smf::UpfResumeRequest &body, Pistache::Http::ResponseWriter &response) = 0;
    virtual void release_pdu_context(const std::string &imsi, const int32_t &pduSessionId, Pistache::Http::ResponseWriter &response) = 0;
};

} // namespace oai::smf_server::api

#endif /* ContextTransferApi_H_ */

