/**
* SMF Internal Context Transfer API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PduSessionContextTransfer.h
 *
 * 
 */

#ifndef PduSessionContextTransfer_H_
#define PduSessionContextTransfer_H_


#include <string>
//#include "Snssai.h"
#include "../../oai-cn5g-common-src/model/common_model/Snssai.h"
#include "Teids.h"
#include "UpfAssociation.h"
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

//namespace oai {
//   namespace model {
//      namespace common {
//         class Snssai;
//      }
//   }
//}

namespace oai::model::smf
{
 // class Snssai;

struct QosFlow {
    uint8_t qfi;
    uint32_t arp;
    // Optional: add mbr/gbr fields if your slice uses them
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(QosFlow, qfi, arp)
};

/// <summary>
/// 
/// </summary>
class  PduSessionContextTransfer
{
public:
    PduSessionContextTransfer();
    virtual ~PduSessionContextTransfer() = default;

    // Orchra
    std::string supi; //imsi;
    uint32_t pdu_session_id;
    std::string dnn;
    std::string ue_ip;

    // Slice & Node Info
    // Snssai snssai;
    // oai::model::common::Snssai m_snssai;
    std::string upf_node_id;
    std::string n4_addr;

    // Control/User Plane IDs
    uint32_t teid_ul;
    uint32_t teid_dl;
    uint64_t seid_upf;
    uint64_t seid_smf;

    // State & Policy
    std::string status; // "paused", "imported", "active"
    std::vector<QosFlow> qos_flows;
    // --- end Orchra --- //

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PduSessionContextTransfer& rhs) const;
    bool operator!=(const PduSessionContextTransfer& rhs) const;

    /////////////////////////////////////////////
    /// PduSessionContextTransfer members

    /// <summary>
    /// 
    /// </summary>
    int32_t getSchemaVersion() const;
    void setSchemaVersion(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    std::string getSupi() const;
    void setSupi(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getPduSessionId() const;
    void setPduSessionId(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    // oai::model::smf::Snssai getSnssai() const;
    oai::model::common::Snssai getSnssai() const;
    // void setSnssai(oai::model::smf::Snssai const& value);
    void setSnssai(oai::model::common::Snssai const& value);
    bool snssaiIsSet() const;
    void unsetSnssai();
    /// <summary>
    /// 
    /// </summary>
    oai::model::smf::UpfAssociation getUpf() const;
    void setUpf(oai::model::smf::UpfAssociation const& value);
    bool upfIsSet() const;
    void unsetUpf();
    /// <summary>
    /// 
    /// </summary>
    oai::model::smf::Teids getTeids() const;
    void setTeids(oai::model::smf::Teids const& value);
    bool teidsIsSet() const;
    void unsetTeids();
    /// <summary>
    /// 
    /// </summary>
    std::string getDnn() const;
    void setDnn(std::string const& value);
    bool dnnIsSet() const;
    void unsetDnn();
    /// <summary>
    /// 
    /// </summary>
    std::string getUeIp() const;
    void setUeIp(std::string const& value);
    bool ueIpIsSet() const;
    void unsetUeIp();

    friend  void to_json(nlohmann::json& j, const PduSessionContextTransfer& o);
    friend  void from_json(const nlohmann::json& j, PduSessionContextTransfer& o);

    // Orchra
    // NLOHMANN_DEFINE_TYPE_INTRUSIVE(PduSessionContextTransfer,
    //    imsi, pdu_session_id, dnn, ue_ip, snssai, upf_node_id,
    //    n4_addr, teid_ul, teid_dl, seid_upf, seid_smf, status, qos_flows)

    // Manually implement these in PduSessionContextTransfer.cpp:
    /*void to_json(nlohmann::json& j, const PduSessionContextTransfer& o) {
	j = nlohmann::json::object({
            {"imsi", o.m_Supi},
            {"pdu_session_id", o.m_PduSessionId},
            {"dnn", o.m_Dnn},
            {"ue_ip", o.m_UeIp},
            {"snssai", o.getSnssai()}, //m_Snssai}, 
            {"status", o.m_Status},
            {"seid_upf", o.m_SeidUpf},
            {"seid_smf", o.m_SeidSmf}
        });
    }*/

    void to_json(nlohmann::json& j, const PduSessionContextTransfer& o) {
        j = nlohmann::json::object();
        j["imsi"]           = o.m_Supi;
        j["pdu_session_id"] = o.m_PduSessionId;
        j["dnn"]            = o.m_Dnn;
        j["ue_ip"]          = o.m_UeIp;
        j["snssai"]         = o.m_Snssai; // nlohmann handles this automatically if Snssai.h is included
        j["status"]         = o.m_Status;
        j["seid_upf"]       = o.m_SeidUpf;
        j["seid_smf"]       = o.m_SeidSmf;
    }

    void from_json(const nlohmann::json& j, PduSessionContextTransfer& o) {
        j.at("imsi").get_to(o.m_Supi);
        j.at("pdu_session_id").get_to(o.m_PduSessionId);
	j.at("dnn").get_to(o.m_Dnn);
	j.at("ue_ip").get_to(o.m_UeIp);
	j.at("status").get_to(o.m_Status);
	j.at("seid_upf").get_to(o.m_SeidUpf);
	j.at("seid_smf").get_to(o.m_SeidSmf);

	if (j.contains("snssai")) {
            oai::model::common::Snssai tempSnssai;
            j.at("snssai").get_to(tempSnssai); 
            o.setSnssai(tempSnssai);          
        }
	/*if(j.find("snssai") != j.end())
        {
            ::oai::model::common::Snssai tempSnssai;
            j.at("snssai").get_to(tempSnssai);
            o.setSnssai(tempSnssai); // This will now match the 'common::Snssai' signature
        }*/
    }

    // --- SEID UPF ---
    uint64_t getSeidUpf() const {
        return m_SeidUpf;
    }

    void setSeidUpf(uint64_t value) {
        m_SeidUpf = value;
    }

    // --- SEID SMF ---
    uint64_t getSeidSmf() const {
        return m_SeidSmf;
    }

    void setSeidSmf(uint64_t value) {
        m_SeidSmf = value;
    }

    // --- STATUS ---
    std::string getStatus() const {
        return m_Status;
    }

    void setStatus(const std::string& value) {
        if (value != "paused" && value != "active") {
            throw std::invalid_argument("Invalid status");
        }
        m_Status = value;
    }

protected:
    int32_t m_SchemaVersion;

    std::string m_Supi;

    int32_t m_PduSessionId;

    bool m_SnssaiIsSet;
    oai::model::smf::UpfAssociation m_Upf;
    bool m_UpfIsSet;
    oai::model::smf::Teids m_Teids;
    bool m_TeidsIsSet;
    std::string m_Dnn;
    bool m_DnnIsSet;
    std::string m_UeIp;
    bool m_UeIpIsSet;
 
    // --- Orchra New Novelty Fields ---
    uint64_t m_SeidUpf;
    uint64_t m_SeidSmf;
    std::string m_Status;     
    //::oai::model::smf::Snssai m_Snssai;
    oai::model::common::Snssai m_Snssai;
};


class PduSessionPauseResponse {
protected:
    oai::model::common::Snssai m_Snssai; 

public:
    // 1. Define sub-structs
    /*
    struct Snssai {
        uint8_t sst;
        std::string sd;
        // 2. Define JSON mapping for the sub-struct
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(Snssai, sst, sd)
    };

    struct Upf {
        std::string node_id;
        std::string n4_addr;
        // 2. Define JSON mapping for the sub-struct
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(Upf, node_id, n4_addr)
    };
    */

    // 3. Main class members
    std::string imsi;
    uint32_t pdu_session_id;
    uint8_t sst;
    std::string sd;
    std::string upf_node_id;
    std::string n4_addr;
    // Snssai snssai;
    // Upf upf;
    std::string dnn;
    std::string ue_ip;
    uint32_t teid_ul;
    uint32_t teid_dl;
    uint64_t seid_upf;
    uint64_t seid_smf;
    std::vector<nlohmann::json> qos_flows;
    std::string status;

    // 4. Now this will work because Snssai and Upf have their own definitions
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(
        PduSessionPauseResponse,
        imsi, pdu_session_id, upf_node_id, n4_addr,
        dnn, ue_ip, teid_ul, teid_dl,
        seid_upf, seid_smf, qos_flows, status
    )
};

} // namespace oai::model::smf

#endif /* PduSessionContextTransfer_H_ */
